version: "3.8"

# stack: volume-s3
#          以全局模式部署 volume-s3，实现基于 S3 的“类 K8s Volume”体验：

networks:
  internal_net:
    driver: overlay
    internal: true

secrets:
  s3_access_key:
    external: true
  s3_secret_key:
    external: true

services:
  volume-s3:
    image: ghcr.io/swarmnative/volume-s3:latest
    networks: [internal_net]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /mnt/s3
        target: /mnt/s3
        bind:
          propagation: rshared
    secrets:
      - s3_access_key
      - s3_secret_key
    environment:
      - VOLS3_ENDPOINT=http://s3.local:9000
      - VOLS3_PROVIDER=
      - VOLS3_RCLONE_REMOTE=S3:your-bucket
      - VOLS3_RCLONE_ARGS=--vfs-cache-mode=writes --dir-cache-time=12h
      - VOLS3_MOUNTPOINT=/mnt/s3
      - VOLS3_ACCESS_KEY_FILE=/run/secrets/s3_access_key
      - VOLS3_SECRET_KEY_FILE=/run/secrets/s3_secret_key
      - VOLS3_PROXY_ENABLE=false
      - VOLS3_NSENTER_HELPER_IMAGE=ghcr.io/swarmnative/volume-s3:latest
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.s3-mounter == true
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 64M
      restart_policy:
        condition: any
      update_config:
        order: start-first
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    read_only: true
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

