name: Build and Publish volume-s3-rclone

on:
  schedule:
    - cron: '0 3 * * 1'  # 每周一 03:00 UTC 定期构建
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (latest)
        uses: docker/build-push-action@v5
        with:
          context: ./volume-s3/images/volume-s3-rclone
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/volume-s3-rclone:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/volume-s3-rclone:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Rclone image for volume-s3 with allow_other enabled
            org.opencontainers.image.licenses=MIT

  cleanup:
    runs-on: ubuntu-latest
    needs: build-push
    permissions:
      packages: write
    steps:
      - name: Delete old container images (keep last 5)
        uses: actions/delete-package-versions@v5
        with:
          package-name: volume-s3-rclone
          package-type: container
          min-versions-to-keep: 5

